export interface SHeaderItems {
  musovvir: any,
  developer: any,
  marker: any,
  addr: any,
  address: any,
  telMarker: any,
  tel: any,
  telephone: any,
  timeMarker: any,
  time: any,
  timeWork: any,
  home: any,
  about: any,
  services: any,
  reviews: any,
  contacts: any,
  search: any,
}
