/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SAboutItems, } from "./components/cnt-flexy-view-viskhan-promo-about-1_01/res/view/cnt-flexy-view-viskhan-promo-about/interface/common.interface";
import { SCarouselItems, } from "./components/cnt-flexy-view-viskhan-promo-carousel-1_01/res/view/cnt-flexy-view-viskhan-promo-carousel/interface/common.interface";
import { SFooterItems, } from "./components/cnt-flexy-view-viskhan-promo-footer-1_01/res/view/cnt-flexy-view-viskhan-promo-footer/interface/common.interface";
import { SHeaderItems, } from "./components/cnt-flexy-view-viskhan-promo-header-1_01/res/view/cnt-flexy-view-viskhan-promo-header/interface/common.interface";
import { SOfferItems, } from "./components/cnt-flexy-view-viskhan-promo-offer-1_01/res/view/cnt-flexy-view-viskhan-promo-offer/interface/common.interface";
import { SServicesItems, } from "./components/cnt-flexy-view-viskhan-promo-services-1_01/res/view/cnt-flexy-view-viskhan-promo-services/interface/common.interface";
import { SSkillsItems, } from "./components/cnt-flexy-view-viskhan-promo-skills-1_01/res/view/cnt-flexy-view-viskhan-promo-skills/interface/common.interface";
export namespace Components {
    interface CntFlexyViewViskhanPromoAbout {
        /**
          * Интерфейс для About
         */
        "SHeaderItems": SAboutItems[];
        /**
          * Данные для About
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoAbout1_01 {
        /**
          * Временный префикс для Image
         */
        "pathToAssets": string;
        /**
          * Данные для About
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoCarousel {
        /**
          * Интерфейс для Carousel
         */
        "SHeaderItems": SCarouselItems[];
        /**
          * Данные для Carousel
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoCarousel1_01 {
        /**
          * Временный префикс для Image
         */
        "pathToAssets": string;
        /**
          * Данные для Carousel
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoFooter {
        /**
          * Интерфейс для Footer
         */
        "SFooterItems": SFooterItems[];
        /**
          * Даныне для Footer
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoFooter1_01 {
        /**
          * Даныне для Footer
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoHeader {
        /**
          * Интерфейс для Header
         */
        "SHeaderItems": SHeaderItems[];
        /**
          * Данные для Header
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoHeader1_01 {
        /**
          * Данные для Header
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoOffer {
        /**
          * Интерфейс для Offer
         */
        "SHeaderItems": SOfferItems[];
        /**
          * Временный префикс для Image
         */
        "pathToAssets": string;
        /**
          * Данные для Offer
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoOffer1_01 {
        /**
          * Временный префикс для Image
         */
        "pathToAssets": string;
        /**
          * Данные для Offer
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoServices {
        /**
          * Интерфейс для Services
         */
        "SServicesItems": SServicesItems[];
        /**
          * Данные для Services
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoServices1_01 {
        /**
          * Данные для Services
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoSkills {
        /**
          * Интерфейс для Offer
         */
        "SSkillsItems": SSkillsItems[];
        /**
          * Данные для Skills
         */
        "payload": any;
    }
    interface CntFlexyViewViskhanPromoSkills1_01 {
        /**
          * Префикс для Image
         */
        "pathToAssets": any;
        /**
          * Данные для Skills
         */
        "payload": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewViskhanPromoAboutElement extends Components.CntFlexyViewViskhanPromoAbout, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoAboutElement: {
        prototype: HTMLCntFlexyViewViskhanPromoAboutElement;
        new (): HTMLCntFlexyViewViskhanPromoAboutElement;
    };
    interface HTMLCntFlexyViewViskhanPromoAbout1_01Element extends Components.CntFlexyViewViskhanPromoAbout1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoAbout1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoAbout1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoAbout1_01Element;
    };
    interface HTMLCntFlexyViewViskhanPromoCarouselElement extends Components.CntFlexyViewViskhanPromoCarousel, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoCarouselElement: {
        prototype: HTMLCntFlexyViewViskhanPromoCarouselElement;
        new (): HTMLCntFlexyViewViskhanPromoCarouselElement;
    };
    interface HTMLCntFlexyViewViskhanPromoCarousel1_01Element extends Components.CntFlexyViewViskhanPromoCarousel1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoCarousel1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoCarousel1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoCarousel1_01Element;
    };
    interface HTMLCntFlexyViewViskhanPromoFooterElement extends Components.CntFlexyViewViskhanPromoFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoFooterElement: {
        prototype: HTMLCntFlexyViewViskhanPromoFooterElement;
        new (): HTMLCntFlexyViewViskhanPromoFooterElement;
    };
    interface HTMLCntFlexyViewViskhanPromoFooter1_01Element extends Components.CntFlexyViewViskhanPromoFooter1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoFooter1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoFooter1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoFooter1_01Element;
    };
    interface HTMLCntFlexyViewViskhanPromoHeaderElement extends Components.CntFlexyViewViskhanPromoHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoHeaderElement: {
        prototype: HTMLCntFlexyViewViskhanPromoHeaderElement;
        new (): HTMLCntFlexyViewViskhanPromoHeaderElement;
    };
    interface HTMLCntFlexyViewViskhanPromoHeader1_01Element extends Components.CntFlexyViewViskhanPromoHeader1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoHeader1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoHeader1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoHeader1_01Element;
    };
    interface HTMLCntFlexyViewViskhanPromoOfferElement extends Components.CntFlexyViewViskhanPromoOffer, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoOfferElement: {
        prototype: HTMLCntFlexyViewViskhanPromoOfferElement;
        new (): HTMLCntFlexyViewViskhanPromoOfferElement;
    };
    interface HTMLCntFlexyViewViskhanPromoOffer1_01Element extends Components.CntFlexyViewViskhanPromoOffer1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoOffer1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoOffer1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoOffer1_01Element;
    };
    interface HTMLCntFlexyViewViskhanPromoServicesElement extends Components.CntFlexyViewViskhanPromoServices, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoServicesElement: {
        prototype: HTMLCntFlexyViewViskhanPromoServicesElement;
        new (): HTMLCntFlexyViewViskhanPromoServicesElement;
    };
    interface HTMLCntFlexyViewViskhanPromoServices1_01Element extends Components.CntFlexyViewViskhanPromoServices1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoServices1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoServices1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoServices1_01Element;
    };
    interface HTMLCntFlexyViewViskhanPromoSkillsElement extends Components.CntFlexyViewViskhanPromoSkills, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoSkillsElement: {
        prototype: HTMLCntFlexyViewViskhanPromoSkillsElement;
        new (): HTMLCntFlexyViewViskhanPromoSkillsElement;
    };
    interface HTMLCntFlexyViewViskhanPromoSkills1_01Element extends Components.CntFlexyViewViskhanPromoSkills1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewViskhanPromoSkills1_01Element: {
        prototype: HTMLCntFlexyViewViskhanPromoSkills1_01Element;
        new (): HTMLCntFlexyViewViskhanPromoSkills1_01Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-viskhan-promo-about": HTMLCntFlexyViewViskhanPromoAboutElement;
        "cnt-flexy-view-viskhan-promo-about-1_01": HTMLCntFlexyViewViskhanPromoAbout1_01Element;
        "cnt-flexy-view-viskhan-promo-carousel": HTMLCntFlexyViewViskhanPromoCarouselElement;
        "cnt-flexy-view-viskhan-promo-carousel-1_01": HTMLCntFlexyViewViskhanPromoCarousel1_01Element;
        "cnt-flexy-view-viskhan-promo-footer": HTMLCntFlexyViewViskhanPromoFooterElement;
        "cnt-flexy-view-viskhan-promo-footer-1_01": HTMLCntFlexyViewViskhanPromoFooter1_01Element;
        "cnt-flexy-view-viskhan-promo-header": HTMLCntFlexyViewViskhanPromoHeaderElement;
        "cnt-flexy-view-viskhan-promo-header-1_01": HTMLCntFlexyViewViskhanPromoHeader1_01Element;
        "cnt-flexy-view-viskhan-promo-offer": HTMLCntFlexyViewViskhanPromoOfferElement;
        "cnt-flexy-view-viskhan-promo-offer-1_01": HTMLCntFlexyViewViskhanPromoOffer1_01Element;
        "cnt-flexy-view-viskhan-promo-services": HTMLCntFlexyViewViskhanPromoServicesElement;
        "cnt-flexy-view-viskhan-promo-services-1_01": HTMLCntFlexyViewViskhanPromoServices1_01Element;
        "cnt-flexy-view-viskhan-promo-skills": HTMLCntFlexyViewViskhanPromoSkillsElement;
        "cnt-flexy-view-viskhan-promo-skills-1_01": HTMLCntFlexyViewViskhanPromoSkills1_01Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewViskhanPromoAbout {
        /**
          * Интерфейс для About
         */
        "SHeaderItems"?: SAboutItems[];
        /**
          * Клик по Me
         */
        "onClickAboutMe"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Musovvir
         */
        "onClickAboutMusovvir"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Text
         */
        "onClickAboutText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Titl
         */
        "onClickAboutTitl"?: (event: CustomEvent<any>) => void;
        /**
          * Данные для About
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoAbout1_01 {
        /**
          * Временный префикс для Image
         */
        "pathToAssets"?: string;
        /**
          * Данные для About
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoCarousel {
        /**
          * Интерфейс для Carousel
         */
        "SHeaderItems"?: SCarouselItems[];
        /**
          * Клик по Titl
         */
        "onClickCarousel"?: (event: CustomEvent<any>) => void;
        /**
          * Данные для Carousel
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoCarousel1_01 {
        /**
          * Временный префикс для Image
         */
        "pathToAssets"?: string;
        /**
          * Данные для Carousel
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoFooter {
        /**
          * Интерфейс для Footer
         */
        "SFooterItems"?: SFooterItems[];
        /**
          * Клик по Email
         */
        "onClickFooterEmail"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Facebook
         */
        "onClickFooterFacebook"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Instagram
         */
        "onClickFooterInstagram"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Telephone
         */
        "onClickFooterTelephone"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Twitter
         */
        "onClickFooterTwitter"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по VK
         */
        "onClickFooterVK"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Youtube
         */
        "onClickFooterYoutube"?: (event: CustomEvent<any>) => void;
        /**
          * Даныне для Footer
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoFooter1_01 {
        /**
          * Даныне для Footer
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoHeader {
        /**
          * Интерфейс для Header
         */
        "SHeaderItems"?: SHeaderItems[];
        /**
          * Клик по Developer
         */
        "onClickHeaderDeveloper"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Info
         */
        "onClickHeaderInfo"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Musovvir
         */
        "onClickHeaderMusovvir"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MyLink
         */
        "onClickHeaderMyLink"?: (event: CustomEvent<any>) => void;
        /**
          * Данные для Header
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoHeader1_01 {
        /**
          * Данные для Header
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoOffer {
        /**
          * Интерфейс для Offer
         */
        "SHeaderItems"?: SOfferItems[];
        /**
          * Клик по Button
         */
        "onClickOfferButton"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickOfferImage"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MyLine
         */
        "onClickOfferMyLine"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MyText
         */
        "onClickOfferMyText"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MyTitl
         */
        "onClickOfferMyTitl"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Titl
         */
        "onClickOfferTitl"?: (event: CustomEvent<any>) => void;
        /**
          * Временный префикс для Image
         */
        "pathToAssets"?: string;
        /**
          * Данные для Offer
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoOffer1_01 {
        /**
          * Временный префикс для Image
         */
        "pathToAssets"?: string;
        /**
          * Данные для Offer
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoServices {
        /**
          * Интерфейс для Services
         */
        "SServicesItems"?: SServicesItems[];
        /**
          * Клик по Icon
         */
        "onClickServiceIcon"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по MyTitl
         */
        "onClickServiceMyTitl"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Titl
         */
        "onClickServiceTitl"?: (event: CustomEvent<any>) => void;
        /**
          * Данные для Services
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoServices1_01 {
        /**
          * Данные для Services
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoSkills {
        /**
          * Интерфейс для Offer
         */
        "SSkillsItems"?: SSkillsItems[];
        /**
          * Клик по Image
         */
        "onClickSkillsImageAngular"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageBs"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageCss"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageHtml"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageJs"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageReact"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageStencil"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Image
         */
        "onClickSkillsImageWp"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Percent
         */
        "onClickSkillsPercent"?: (event: CustomEvent<any>) => void;
        /**
          * Клик по Titl
         */
        "onClickSkillsTitl"?: (event: CustomEvent<any>) => void;
        /**
          * Данные для Skills
         */
        "payload"?: any;
    }
    interface CntFlexyViewViskhanPromoSkills1_01 {
        /**
          * Префикс для Image
         */
        "pathToAssets"?: any;
        /**
          * Данные для Skills
         */
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-viskhan-promo-about": CntFlexyViewViskhanPromoAbout;
        "cnt-flexy-view-viskhan-promo-about-1_01": CntFlexyViewViskhanPromoAbout1_01;
        "cnt-flexy-view-viskhan-promo-carousel": CntFlexyViewViskhanPromoCarousel;
        "cnt-flexy-view-viskhan-promo-carousel-1_01": CntFlexyViewViskhanPromoCarousel1_01;
        "cnt-flexy-view-viskhan-promo-footer": CntFlexyViewViskhanPromoFooter;
        "cnt-flexy-view-viskhan-promo-footer-1_01": CntFlexyViewViskhanPromoFooter1_01;
        "cnt-flexy-view-viskhan-promo-header": CntFlexyViewViskhanPromoHeader;
        "cnt-flexy-view-viskhan-promo-header-1_01": CntFlexyViewViskhanPromoHeader1_01;
        "cnt-flexy-view-viskhan-promo-offer": CntFlexyViewViskhanPromoOffer;
        "cnt-flexy-view-viskhan-promo-offer-1_01": CntFlexyViewViskhanPromoOffer1_01;
        "cnt-flexy-view-viskhan-promo-services": CntFlexyViewViskhanPromoServices;
        "cnt-flexy-view-viskhan-promo-services-1_01": CntFlexyViewViskhanPromoServices1_01;
        "cnt-flexy-view-viskhan-promo-skills": CntFlexyViewViskhanPromoSkills;
        "cnt-flexy-view-viskhan-promo-skills-1_01": CntFlexyViewViskhanPromoSkills1_01;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-viskhan-promo-about": LocalJSX.CntFlexyViewViskhanPromoAbout & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoAboutElement>;
            "cnt-flexy-view-viskhan-promo-about-1_01": LocalJSX.CntFlexyViewViskhanPromoAbout1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoAbout1_01Element>;
            "cnt-flexy-view-viskhan-promo-carousel": LocalJSX.CntFlexyViewViskhanPromoCarousel & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoCarouselElement>;
            "cnt-flexy-view-viskhan-promo-carousel-1_01": LocalJSX.CntFlexyViewViskhanPromoCarousel1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoCarousel1_01Element>;
            "cnt-flexy-view-viskhan-promo-footer": LocalJSX.CntFlexyViewViskhanPromoFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoFooterElement>;
            "cnt-flexy-view-viskhan-promo-footer-1_01": LocalJSX.CntFlexyViewViskhanPromoFooter1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoFooter1_01Element>;
            "cnt-flexy-view-viskhan-promo-header": LocalJSX.CntFlexyViewViskhanPromoHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoHeaderElement>;
            "cnt-flexy-view-viskhan-promo-header-1_01": LocalJSX.CntFlexyViewViskhanPromoHeader1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoHeader1_01Element>;
            "cnt-flexy-view-viskhan-promo-offer": LocalJSX.CntFlexyViewViskhanPromoOffer & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoOfferElement>;
            "cnt-flexy-view-viskhan-promo-offer-1_01": LocalJSX.CntFlexyViewViskhanPromoOffer1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoOffer1_01Element>;
            "cnt-flexy-view-viskhan-promo-services": LocalJSX.CntFlexyViewViskhanPromoServices & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoServicesElement>;
            "cnt-flexy-view-viskhan-promo-services-1_01": LocalJSX.CntFlexyViewViskhanPromoServices1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoServices1_01Element>;
            "cnt-flexy-view-viskhan-promo-skills": LocalJSX.CntFlexyViewViskhanPromoSkills & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoSkillsElement>;
            "cnt-flexy-view-viskhan-promo-skills-1_01": LocalJSX.CntFlexyViewViskhanPromoSkills1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewViskhanPromoSkills1_01Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
